### ISSUE TITLE
How can find out the text message the reply is related to?

### ISSUE THREAD

**Issue by Hirurg103** [esendex/esendex-ruby-sdk#13]
I have the following problem:

For example if I send to a user 2 text messages

- Something happened in Egypt - 1st message
- Today is the Ales' birthday! - 2nd message

and the user replies

- Yes, I know!

can I find out which message the reply is related to?

**Comment by moretonb** [comment]
Hi @Hirurg103,

If both the messages came in to the same VMN you would struggle to understand which one the reply was for. On the actual handset both messages would appear to be part of the same conversation too.

A work around would be to set up a second account with a second VMN and split the messages you want to send between the accounts. Then you would be able to tie up the reply.

**Comment by Hirurg103** [comment]
Hello @moretonb,

thank you, different VMN is a good idea. We were looking for how to solve the described problem with single VMN

There is esendex support reply to this issue:

> Hi,
> 
> Thank you for your email.
> 
> Unfortunately in the scenario there isn't an easy way to do this, as the inbound SMS has no relation to the outbound sms unless you request they reply with a code.
> 
> Most customers use Multiple Virtual mobile numbers for this, so that they can rotate them.
> 
> Thanks

Also we asked esendex support if it is possible to send some identifier with the message:

> To: support@esendex.com
> 
> Hello,
> 
> thank you for the reply.
> 
> I have another question related to this issue:
> Can we send additional custom fields with sms notification?
> For example, we send custom field \<notification_id\>9090\</notification_id\> with other SMS fields
> and this custom field comes back to us with the user's reply. Then we can easily identify SMS
> the reply is related to
> 
> Thanks

This is what they replied:

> Hi,
> 
> Thank you for your response.
> 
> Unfortunately there isn't anywhere to store this within our system, and as such they would be ignored.
> 
> Thanks,
> 
> Support Queue ROW
